# Section 3 NumPy

## Part One

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mymatrix= np.array(mylist)

In [10]:
mymatrix.shape

(3, 3)

In [11]:
mynewmatrix = np.array(mylist)

In [12]:
mynewmatrix.dtype

dtype('int32')

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(0.0)

float

In [18]:
type(0.)

float

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [22]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [23]:
[1,1,1,1] * 100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [24]:
[1,1,1,1]+10

TypeError: can only concatenate list (not "int") to list

In [25]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [27]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Part Two

In [30]:
np.random.rand(1)

array([0.07455217])

In [31]:
np.random.rand(4)

array([0.81656576, 0.10947744, 0.52014152, 0.54789168])

In [32]:
np.random.rand(5,5)

array([[0.86511741, 0.14396996, 0.21331334, 0.45664508, 0.88234953],
       [0.24815604, 0.06008971, 0.34326812, 0.39158684, 0.32217264],
       [0.53647045, 0.94439845, 0.1551319 , 0.34038204, 0.11199499],
       [0.03943181, 0.63244835, 0.55468357, 0.48098543, 0.72011863],
       [0.87671685, 0.85737314, 0.82491722, 0.97605721, 0.9399056 ]])

In [33]:
np.random.randn(1)

array([0.0534313])

In [34]:
np.random.randn(10)

array([ 1.57402492,  0.03488894, -1.22313827, -1.65777406, -0.4640095 ,
       -0.54567197,  1.03191378,  2.04293513,  0.16819807,  2.48244335])

In [35]:
#np.random.normal()

In [36]:
np.random.randint(1,100)

33

In [37]:
np.random.randint(1,100,10)

array([31, 87, 10, 46, 14, 90, 76,  7, 92,  2])

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [40]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [44]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [45]:
arr.shape

(25,)

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.max()

48

In [48]:
ranarr.min()

10

In [49]:
ranarr.argmax()

1

In [50]:
ranarr.argmin()

6

In [51]:
ranarr.dtype

dtype('int32')

## Indexing and selection

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
arr[:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [60]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [61]:
new_arr = arr / 2

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [64]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

-------

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:6]

In [67]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [68]:
slice_of_arr[:] = 99

In [69]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy = arr.copy()

In [72]:
arr_copy[:] = 10000

In [73]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing on 2D array

In [75]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
arr_2d.shape

(3, 3)

In [78]:
arr_2d[1]

array([20, 25, 30])

In [79]:
arr_2d[1][1]

25

In [80]:
arr_2d[1,1]

25

#### little exercise, get number 45 from the array

In [81]:
arr_2d[2,2]

45

In [82]:
arr_2d[2][2]

45

#### -----------------

In [83]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
arr = np.arange(1,11) 

In [86]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
bool_arr = arr > 4

In [89]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [92]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

---

## NumPy Operations

In [93]:
arr = np.arange(0,10)

In [94]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [96]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [97]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [98]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [99]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
1/arr

C:\Users\BMonti\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [102]:
arr/arr

C:\Users\BMonti\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [104]:
np.log(arr)

C:\Users\BMonti\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [105]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [106]:
arr.sum()

45

In [107]:
arr.mean()

4.5

In [108]:
arr.max()

9

In [109]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [110]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
arr_2d.shape

(3, 4)

In [112]:
arr_2d.sum()

78

In [114]:
arr_2d.sum(axis=0) #sum across the rows -> generate the sum of each value in the columns 

array([15, 18, 21, 24])

In [115]:
arr_2d.sum(axis=1) #sum across the columns --> generate the sum of each value in the rows 

array([10, 26, 42])

----

Exercises in another notebook by filename 03-NumPy-Exercises.ipynb